### ISSUE TITLE
[Fix] 나의 예약 페이지 에러

### ISSUE THREAD

**Issue by mgn1440** [mgn1440/JabTraining#46]
<img width="405" alt="스크린샷 2024-10-16 오후 6 34 09" src="https://github.com/user-attachments/assets/d508451f-783a-4a0e-89bf-23fcec52cb1b">

**Comment by mgn1440** [comment]
이 오류는 아직 있습니다

**Comment by sunko-seoul** [comment]
에러 수정했습니다
